version: '3.8'


services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackend
    container_name: friend_auto_backend
    restart: always
    env_file:
      - .env
    volumes:
      - "mediafiles:/app/backend/media"
    ports:
      - "8080:8080"
    networks:
      proj_network:
        ipv4_address: 172.16.1.2

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontend
    container_name: friend_auto_frontend
    restart: always
    ports:
      - "5173:5173"
    networks:
      proj_network:
        ipv4_address: 172.16.1.4

  nginx:
    build:
      context: ./nginx
      dockerfile: DockerfileNginx
    container_name: friend_auto_nginx
    volumes:
      - "mediafiles:/media"
    ports:
      - "80:80"
    networks:
      proj_network:
        ipv4_address: 172.16.1.9
    depends_on:
      - backend
      - frontend


networks:
  proj_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24


volumes:
  mediafiles:
