name: Full-App-CD

on:
  push:
    branches: [ "main" ]

jobs:
  checkout-changes:
    runs-on: self-hosted

    env:
      DEBUG: 'True'
      ALLOWED_HOSTS: '*'
      IP_OR_DNS_SERVER: '188.225.36.185'
      DB_HOST: '172.17.0.1'

    steps:
      - uses: actions/checkout@v3

      - name: Write Django Env
        run: |
          echo "DJANGO_SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}'" >> .env
          echo "DEBUG=${{ env.DEBUG }}" >> .env
          echo "ALLOWED_HOSTS='${{ env.ALLOWED_HOSTS }}'" >> .env
          echo "IP_OR_DNS_SERVER='${{ env.IP_OR_DNS_SERVER }}'" >> .env
          echo "MAIN_ADMIN_USERNAME='${{ secrets.MAIN_ADMIN_USERNAME }}'" >> .env
          echo "MAIN_ADMIN_PASSWORD='${{ secrets.MAIN_ADMIN_PASSWORD }}'" >> .env

      - name: Write DB Env
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_USER_PASSWORD=${{ secrets.DB_USER_PASSWORD }}" >> .env
          echo "DB_HOST=${{ env.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

  deploy:
    runs-on: self-hosted
    needs: [ checkout-changes ]

    steps:
      - name: Deploy updated repo
        run: |
          docker-compose --file ./docker-compose.yml down
          docker-compose --file ./docker-compose.yml up --build -d
